server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: 34.87.156.153
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:34.87.156.153}:${EUREKA_PORT:8761}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

logging:
  level:
    org.springframework: INFO
