spring:
  application:
    name: infrastructure-service
  kafka:
    bootstrap-servers: 34.124.129.117:9092
    application-id: infrastructure-service
    properties:
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      offset:
        reset: earliest
      commit:
        interval:
          ms: 100

  datasource:
    url: jdbc:postgresql://34.142.187.195:3242/testingdb
    username: springdb
    password: ITE2@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jenkins:
  url: http://34.142.187.195:8080
  username: asura
  password: 11cae77a9e032f7f2ebd9b82e75aeb087e
  log:
    topic: jenkins-logs


server:
  port: 8085

name:
  com:
    api:
      token: 2654afc89abd16d01213a0fecadee55cded0ef7b
      username: vannraruos@gmail.com

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.87.156.153:8761/eureka/